name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2

  
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    
    - name: Set up Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

  
    - name: Terraform Init
      run: terraform init
      working-directory: ./Terraform-Loganalytics

   
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Terraform-Loganalytics

 
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan
      working-directory: ./Terraform-Loganalytics

   
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./Terraform-Loganalytics
