name: Terraform Azure Deployment

on:
  push:
  #workflow_dispatch:  
    #branches:
    #  - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout Repository
      uses: actions/checkout@v2

  
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    
    - name: Set up Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Export ARM environment variables
      run: |
          echo "ARM_CLIENT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).subscriptionId }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}" >> $GITHUB_ENV


  
    - name: Terraform Init
      run: terraform init
      working-directory: ./Terraform-Loganalytics

   
    - name: Terraform Validate
      run: terraform validate
      working-directory: ./Terraform-Loganalytics

 
    - name: Terraform Plan
      id: plan
      run: terraform plan -out=tfplan.out
      working-directory: ./Terraform-Loganalytics

    - name: Run Infracost Breakdown
      run: |
          INFRACOST_API_KEY: ${{secrets.INFRACOST_API_KEY}}  
          infracost breakdown --path tfplan.out --format json > infracost_output.json

    - name: Upload Infracost Output as Artifact
      uses: actions/upload-artifact@v4
      with:
          name: infracost-output
          path: infracost_output.json


    
   
    #- name: Terraform Apply
    #  run: terraform apply -auto-approve tfplan
    #  working-directory: ./Terraform-Loganalytics
