name: Terraform Azure Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.5.0

    # Set up Azure Credentials using GitHub Secrets
    - name: Set up Azure Credentials
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init

    # Validate the Terraform code
    - name: Terraform Validate
      run: terraform validate

    # Run Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan

    # Apply Terraform Plan
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
